// catalogos.js - Archivo central de catálogos

const catEntidades = [
    "01 Aguascalientes",
    "02 Baja California",
    "03 Baja California Sur",
    "04 Campeche",
    "05 Coahuila",
    "06 Colima",
    "07 Chiapas",
    "08 Chihuahua",
    "09 Ciudad de México",
    "10 Durango",
    "11 Guanajuato",
    "12 Guerrero",
    "13 Hidalgo",
    "14 Jalisco",
    "15 México",
    "16 Michoacán",
    "17 Morelos",
    "18 Nayarit",
    "19 Nuevo León",
    "20 Oaxaca",
    "21 Puebla",
    "22 Querétaro",
    "23 Quintana Roo",
    "24 San Luis Potosí",
    "25 Sinaloa",
    "26 Sonora",
    "27 Tabasco",
    "28 Tamaulipas",
    "29 Tlaxcala",
    "30 Veracruz",
    "31 Yucatán",
    "32 Zacatecas"
];

const catJurisdicciones = [
    "01 Piedras Negras", "02 Acuña", "03 Sabinas", "04 Monclova", 
    "05 Cuatro Ciénegas", "06 Torreón", "07 Francisco I. Madero", "08 Saltillo"
];

const catMunicipios = [
    "003 Allende",
    "012 Guerrero",
    "013 Hidalgo",
    "022 Nava",
    "025 Piedras Negras",
    "037 Villa Unión",
    "002 Acuña",
    "014 Jiménez",
    "019 Morelos",
    "038 Zaragoza",
    "015 Juárez",
    "020 Múzquiz",
    "026 Progreso",
    "028 Sabinas",
    "032 San Juan De Sabinas",
    "001 Abasolo",
    "005 Candela",
    "006 Castaños",
    "008 Escobedo",
    "010 Frontera",
    "018 Monclova",
    "021 Nadadores",
    "031 San Buenaventura",
    "007 Cuatro Ciénegas",
    "016 Lamadrid",
    "023 Ocampo",
    "029 Sacramento",
    "034 Sierra Mojada",
    "017 Matamoros",
    "035 Torreón",
    "036 Viesca",
    "009 Francisco I. Madero",
    "033 San Pedro",
    "004 Arteaga",
    "011 General Cepeda",
    "024 Parras",
    "027 Ramos Arizpe",
    "030 Saltillo"
];

// AQUÍ PEGAS TUS 400 AGEBs
const catAGEBs = [
    "Acueducto, Los Arcos - 281-2",
    "Aeropuerto - 060-9",
    "Alfredo B. Bonfil - 236-7",
    "Altos de Bella Unión - 037-5",
    "América - 148-1",
    "Ampliación María de León - 521-5",
    "Ampliación Morelos, La Amistad y Balcones de Morelos - 544-6",
    "Ampliación Morelos - 543-1",
    "Anahuac, Isabel Amalia - 216-A",
    "Analco - 153-7",
    "Analco I, Armillita, Peña Alta - 154-1",
    "Analco II, Jardínes de Analco - 160-7",
    "Antonio Cáras, Cerro del Pueblo - 014-4",
    "Arboledas y Paraíso - 167-4",
    "Asturias, Nuevo México (Solo realiza escuelas) - 481-9",
    "Autopista - 047-9",
    "Ayuntamiento, San Isidro, Partición, Loma Azul, San Francisco - 018-2",
    "Balcones de las Torres - 572-8",
    "Balcones de Santa Fé, Manantiales - 164-5",
    "Baldío - 042-6",
    "Bella Unión - 037-6",
    "Bella Unión (Parte) - 041-1",
    "Bellavista, Burócratas del Estadoy Ojo de Agua (Morelos - Abasolo - Primo de Verdad - Feliz u. Gómez - Vicente Rangel) - 262-A",
    "Bellavista, Miramontes y Burócratas del Estado (Ojo de Agua - Escobedo - Simón Bolivar (Nones) - Hidalgo - Vicente Rangel) - 256-4",
    "Bellavista - 300-7",
    "Bonanza - 213-6",
    "Buena Vista, Emiliano Zapata - 188-6",
    "Buenos Aires y Genaro Vázquez, Balcones de Bellavista - 284-6",
    "Buenos Aires y Ampliación Buenos Aires - 278-0",
    "Burócratas Municipales y 26 de Marzo - 292-0",
    "Cáctus, Emiliano Zapata, Urbivillas, Analco II - 159-4",
    "Calle Santa Rosalia (A lado de la Amistad) - 522-A",
    "Calle Valle Alegre hasta Valle de Iguana, Chalco, Martha Gutiérrez hasta el #325 - 162-6",
    "Cañón de San Lorenzo, Fracc. Las Rosas - 553-5",
    "Centenario (Centro de Salud Los González) - 264-9",
    "Centenario, Benito Juárez, Magisterio, Sección 38 (Abasolo - 26 de Marzo, J. Mery - 20 de Noviembre, Pedro Valle - Rómulo Hernández) - 266-8",
    "Centro de Salud Asturias, Nuevo México, Portal de Asturias (IMSS 91 Escuelas) - 481-9",
    "Centro de Salud Jerusalem - 458-A",
    "Centro (Muzquiz - Coss, Abasolo - Gral. Cepeda) - 018-2",
    "Chamizal (Guayulera), Luis Cortines - 035-6",
    "Ciudad Las Torres - 569-6",
    "Ciudad Mirasierra, Real del Sol 1a y 2a etapa - 415-1",
    "Col. Benito Juárez, Fracc. El Papalote, Fracc. Los Alamitos, Col. La Madrid - 271-9",
    "Col. Agua Nueva - 457-5",
    "Col. Australia 454-5",
    "Col. La Madrid - 272-3",
    "Col. 10 de Mayo, Lomas de Santa Cruz, Portal del Sur - 503-7",
    "Col. Lomas de Guadalupe - 277-6",
    "Col. Los Rosarios, La Joyita, Santa Teresa - 435-9",
    "Col. Valle Verde, Julieta Pérez - 532-3",
    "Col. Bellavista, Fracc. Héroes de Chapultepec - 273-8",
    "Col. Los Cuiernitos, El Bosque - 432-5",
    "Col. Lucio Blanco, Fracc. Quinta Valle, Parque V. Carranza, Central Camionera - 279-5",
    "Col. Ricardo Flores Magón, Agua Nueva - 438-2",
    "Col. Ricardo Flores Magón, Jesús Corona, Nueva Reforma - 437-8",
    "Col. Roma - 427-4",
    "Col. San Juan - 456-0",
    "Col. 5 de Mayo, San Isidro, Los Pinos - 434-4",
    "Colinas de San Fco. - 468-3",
    "Colinas de Santiago - 586-A",
    "Colinas de Santiago - 585-5",
    "Colinas del Sur y Colinas de San Lorenzo - 502-2",
    "Conjunto Habitaciónal, Adolfo López Mateos - 426-A",
    "Conquistadores, Fundadores, Vista Hermosa y Morelos - 250-7",
    "Cumbres, Ampl. Valle San Antonio, Parte Obrera y Loma Dorada - 406-2",
    "Col. González - 257-9",
    "Col. Azteca, Gustavo Espinoza Mireles, Mitras - 224-4",
    "Condominios, Herradura - 470-0",
    "Conjunto Habitacional, Francisco U. Madero - 200-9",
    "Cañón de San Lorenzo - 475-3",
    "Conquistadores, Funddores, Vista Hermosa, La Fuente y Morelos - 158-5",
    "Col. Ojo de Agua, Unidad Habitacional Fco. I Madero, Col. Bellavista - 039-4",
    "Conquistadores, Fundadores y Vista Hermosa - 246-0",
    "Cipreses, El Rosario, Tulipanes, El Baluarte, La Hibernia - 500-3",
    "De Acero - 170-0",
    "Doctores, Alpes, Rancho de Peña, Real de Peña, San Isidro, Ampliación Doctores y Privada San Carlos - 127-A",
    "Doctores y Alpes - 197-5",
    "Doctores y Las Cabañas, Fracc. Los Lagos - 196-0",
    "Ejidal - 022-9",
    "Ejidal (Parte) - 040-7",
    "Ejido La Minita - 471-5",
    "El Álamo - 439-7",
    "El Campanario, Las Granjas y Panteón San Arcángel - 399-0",
    "El Nogalar - 020-A",
    "El Salvador, Fundadores de la Libertad - 447-1",
    "Escorial I - 138-2",
    "Escorial II - 155-6",
    "Estrella de David, 4 de Octubre, Canoa - 049-8",
    "Estrella y Humberto Dávila - 488-0",
    "Estrella y Villas de San Lorenzo - 487-6",
    "Evaristo Madero, San Ramón - 244-1",
    "Evaristo Pérez Arreóla, Col. Nuevo Amanecer, Valencia - 568-1",
    "Federico Berrueto Ramón - 504-1",
    "Fidel Velázquez - 065-1",
    "Fidel Velázquez - 066-6",
    "Flora Ortega, Valle Satélite - 573-2",
    "Florencia - 398-6",
    "Fortín de Carlota y San Lorenzo - 037-5",
    "Fracc. Fco. I. Madero, Prados de San José - 412-8",
    "Fracc. Loma Linda - 495-0",
    "Fracc. Santa Barbara - 384-4",
    "Fracc. El Sauz - 385-9",
    "Fracc. Agua Azul - 252-6",
    "Fracc. Alameda (Centro de Salud Madero) - 027-1",
    "Fracc. Doctores 3° Ampliación - 429-3",
    "Fracc. Luis Cortines, Fracc. Chamizal - 036-0",
    "Fracc. Saltillo - 437-5",
    "Fracc. San Vicente y Valle de Santa Elena - 171-0",
    "Fracc. Burócratas del Estado, Balcones de Bellavista, Bellavista - 040-7",
    "Fracc. Miguel Hidalgo - 287-6",
    "Fracc. Miravalle - 280-8",
    "Fracc. Lomas Verdes - 513-0",
    "Fracc. Luis Donaldo Colosio - 300-7",
    "Fracc. Parajes de Santa Elena - 554-A",
    "Fracc. Nuestra Señora de Fátima - 137-6",
    "Fracc. Santiago, Fracc. Villa Olímpica, Virreyes - 165-6",
    "Fracc. Las Haciendas - 282-2",
    "Fracc. Virreyes Pensiones - 191-8",
    "Fracc. La Salle - 203-2",
    "Fracc. Las Haciendas y Villa Universidad - 287-7",
    "Fracc. La Noria, Villa Vergel, Fracc. Brisas - 314-9",
    "Fracc. Latinoamericana - 204-7",
    "Fracc. Ocenaía - 210-2",
    "Fracc. Oceanía Blvd - 211-7",
    "Fracc. Portal de Aragón - 198-A",
    "Fracc. Priv. Las Palmas, Fracc. Villa Toscana - 548-4",
    "Fracc. Priv. Los Magueyes, Lomas del Bosque - 564-3",
    "Fracc. Plaza, Villas del Camino Real - 551-6",
    "Fracc. Portal del Quijote y Saltillo 2000 - 542-7",
    "Fracc. San Agustín - 428-9",
    "Fracc. San Lorenzo, Col. Bellavista - 038-A",
    "Fracc. Santa María, Jardínes del Valle - 227-8",
    "Fracc. Tulipanes, Cipreses, El Rosario - 503-3",
    "Fracc. Valle Universidad, Fracc. Paraíso - 217-4",
    "Fracc. Villa Olímpica y Virreyes Olímpica - 195-6",
    "Fracc. Virreyes Residencial, Río Bravo - 515-A",
    "Fracc. Virreyes Residencial - 192-2",
    "Fracc. Zapalinamé - 243-7",
    "Fracc. Zapalinamé, Fracc. San Esteban, Fracc. Urdiñola - 249-4",
    "Francisco Villa, Valle de las Flores Pop - 235-2",
    "Fundadores Vista Hermosa, Morelos y Cecilia Ocheli - 254-5",
    "Fundadores Vista Hermosa, Morelos y Cecilia Ocheli - 255-A",
    "Fundadores y Vista Hermosa - 260-0",
    "Fundadores y Vista Hermosa - 268-7",
    "Fundadores y Vista Hermosa (Priv. San Javier) - 276-1",
    "Fundadores y Vista Hermosa (Lomas de San Francisco) - 312-A",
    "Gaspar Valdéz - 545-0",
    "Girasol y Gpe. Victoria (Centro de Salud Girasol) - 291-6",
    "Guanajuato Oriente y Olmo, Fracc. Los Adoves - 219-3",
    "Guayulera, Brisas del Valle, Beta Centaura y parte Providencia - 248-A",
    "Guayulera, Chamizal - 041-1",
    "Gustavo Espinoza Mireles - 215-5",
    "Gustavo Díaz Ordaz, Nueva Libertad - 431-0",
    "Gustavo Espinoza Mireles - 266-3",
    "Hacienda El Cortijo, El Ranchito - 299-2",
    "Hacienda las Isabeles, Villas de la Angostura - 552-0",
    "Hacienda las Magueyadas, Pueblo Insurgentes - 202-8",
    "Hacienda II, Del Valle, Lomas del Valle, Elsa Hernández - 062-8",
    "Hacienda Narro - 315-3",
    "Hacienda Narro - 472-1",
    "Hacienda San Rafael - 486-1",
    "Hacienda, Hacienda I - 071-1",
    "Hacienda III - 070-2",
    "Héroes deLa Revolución, Salomón Abedrop - 480-4",
    "Hospital General (Centro Metropolitano) y Parque las Maravillas - 162-1",
    "Ignacio Allende, Obrera, Independencia - 489-5",
    "Independencia, Oscar Flores Tapia, Anahuac, Cerro del Pueblo - 490-8",
    "Isabel Amalia - 225-9",
    "I.T.E.S.M. y Rancho los Pepi - 207-0",
    "Jardínes Coloniales, Residencial Priv. Santiago - 301-1",
    "Jardínes del Bosque, Santa Cristina - 383-A",
    "Jardínes del Lago, Rancho Las Varas y Centro - 013-A",
    "Jardínes del Valle - 228-2",
    "Josefa Ortíz de Domínguez - 231-4",
    "Josefa Ortíz de Domínguez, Puerto Las Flores - 498-4",
    "Jurisdicción 8 - 514-5",
    "La Amistad - 465-A",
    "La Aurora, San Patricio, Priv. Guarnición y Priv. Plácido Glz. - 152-8",
    "La Amistad - 478-7",
    "La Amistad - 526-8",
    "La Gloria, Col. San Isidro, Fracc. Valencia - 567-7",
    "La Herradura - 388-2",
    "La Libertad del Puente, La Aurora, Nueva Aurora, La Herradura, Balcones de la Aurora - 139-2",
    "La Minita, Tanquesito - 159-A",
    "La Palma y Rosaleda - 259-8",
    "La Madrid - 274-2",
    "La Palmilla, Hibernia, Granja Batalla y Cortijo La Joya - 381-0",
    "La Rosaleda, Las Palmas - 259-8",
    "La Florida y Bonanza - 212-1",
    "Las Aves - 455-6",
    "Las Haciendas - 282-7",
    "Las Margaritas - 499-9",
    "Las Torres - 511-1",
    "Las Torres - 519-8",
    "Loma, Eulalio Gutiérrez, Fracc. Del Bosque, Campanario, Molinos del Rey - 068-5",
    "Loma Linda - 528-7",
    "Lomas de Lourdes - 472-A",
    "Lomas de Lourdes, Fracc. Lomas del Sur - 182-9",
    "Lomas de San Javier, Nogales - 507-5",
    "Las Golondrinas - 373-6",
    "Loma Linda - 518-3",
    "La Peñita - 433-A",
    "Los Fresnos - 232-9",
    "Los González, Los Silleres y Puerta de Santa Martha - 380-6",
    "Los González, Misiones, Lomas de Peña, San Juan Bautista, Fracc. La Rosa - 387-8",
    "Los Rodríguez, Las Huertas, Valle Hermoso y Puerta del Sol - 122-7",
    "Los Valdez, Casa Cuna, Jardínes de Versalles y González - 316-8",
    "Lomas de Lourdes - 298-8",
    "Lomas de Lourdes - 473-4",
    "Lomas Verdes, Valle Dorado, Lomas de Lourdes - 534-2",
    "Las Quintas y Jardínes Coloniales - 375-5",
    "Latinoamericana y Cumbres - 206-6",
    "Latinoamericana, Jardín oriente, Los Ángeles y Alpes - 205-1",
    "Loma Bonita, Parajes Oriente, Jesús Cabello - 446-7",
    "Loma Linda - 560-5",
    "Lomas de Europa - Los Cedros - 050-0",
    "Lomas del Pedregal, Portal del Pedregal - 574-7",
    "Lomas del Pedregal y Villas de Santiago - 443-3",
    "Lomas del Refugio - 523-4",
    "Lomas del Refugio - 555-4",
    "Lomas Verdes - 448-6",
    "Lomas Verdes - 505-6",
    "Lomas de Zapalinamé, Lomas de San Francisco - 453-7",
    "Lomas de Zapalinamé - 452-2",
    "Los Pinos - 463-0",
    "Los Pinos - 464-5",
    "Luis Donaldo Colosio - 046-4",
    "Magisterio - 229-7",
    "Magisterio - 230-A",
    "Manantiales del Valle - 150-3",
    "María de León - 461-1",
    "María de León - 479-1",
    "Mercado de Abastos - 245-6",
    "Mesa de las Cabras - 043-0",
    "Meza de Lourdes, Buitres - 459-4",
    "Meza de Lourdes y Buitres - 459-4",
    "Mirador y Brisas del Valle - 242-2",
    "Mirador, Cañadas del Mirador - 075-5",
    "Mirasierra - 512-6",
    "Mirasierra - 520-0",
    "Mirasierra - 561-A",
    "Mirasierra, Real del Sol 2da. etapa - 576-6",
    "Mirasierra, Zaragoza - 467-9",
    "Misión Cerritos, Prados de San José - 008-9",
    "Misión Cerritos - 557-3",
    "Misión Santa Lucía, Misión Cerritos - 556-9",
    "Miguel Hidalgo - 290-1",
    "Miguel Hidalgo y Villa Universidad - 287-A",
    "Molinos de Belén, La Condesa - 253-0",
    "Monte del Sanai - 562-4",
    "Monte Sion (A lado de la Amistad), Sinai, San Ignacio - 525-3",
    "Morelos, Ampl. Morelos y 10 de Abril (Centro de Salud Morelos) - 261-5",
    "Morelos, Ampliación Vista Hermosa - 537-6",
    "Morelos, Ampl. Morelos, 15 de Septiembre y Solidaridad - 269-1",
    "Morelos, Ampliación Vista Hermosa - 538-0",
    "Nazario Ortíz Garza, La Purísima - 485-7",
    "Nogales - 506-0",
    "Nogalera, Capellania - 077-4",
    "Niños Héroes (Cañón de San Lorenzo) - 477-2",
    "Niños Héroes (Cañón de San Lorenzo) - 524-9",
    "Nogalera de Campestre y Las Cabañas , Loma Blanca, Capellania - 317-2",
    "Nueva Imágen y La Morita - 390-A",
    "Nueva Jerusalén 458-A",
    "Nueva Revolución - 251-1",
    "Nueva Revolución - 454-1",
    "Nueva Tlaxcala - 442-9",
    "Nuevo Mirasierra - 527-2",
    "Nuevo Mirasierra - 579-A",
    "Nuevo Ramos - 137-8",
    "Olímpica, Jardín, Parques y Los Ángeles - 133-5",
    "Olivos, Fracc. La Fragua, La Rosa, Cruz del Aire - 501-8",
    "Omega, Fracc. Rincón de Asturias - 482-3",
    "Padre Santos, Ejido La Vega - 405-8",
    "Parajes de los Pinos - 173-4",
    "Parajes de Santa Elena - 577-0",
    "Parajes del Valle - 162-6",
    "Parajes del Valle - 168-3",
    "Parque Industrial, Villa de Santa María - 151-8",
    "Parques de la Cañada - 296-9",
    "Parques de la Cañada 297-3",
    "Paseo de la Piedad - 161-1",
    "Patria Libre, Fracc. Priv. Obregón, Jesús Corona, Nueva Reforma - 437-8",
    "Periodistas y Eulario Gutiérrez - 295-4",
    "Peña Alta, La Palma, Anacahuita, Jardín, Año de Juárez - 059-6",
    "Postal Cerritos - 441-4",
    "Portal de Agaves - 128-4",
    "Portal de Aragón - 208-5",
    "Praderas - 221-0",
    "Priv. Emilio Carranza - 015-9",
    "Popular Loma Blanca, Puerta de Oriente - 558-8",
    "Postal Cerritos, Nogalar y Candelarias - 157-0",
    "Provivienda - 021-4",
    "Puerta de Oriente - 496-5",
    "Puerta de Lourdes y Lomas de Lourdes - 533-8",
    "Puerto de Flores - 409-6",
    "Puerto La Virgen - 530-4",
    "Rancho de Ana María, Granja Gloria y Los Valdéz, Villa Magna - 376-A",
    "Rincón de Guadalupe, Valle de las Flores Popular y parte de V. Carranza Sur - 240-3",
    "República y Quinta Los Ángeles - 006-A",
    "República I.S.S.S.T.E - 007-4",
    "República Norte y Oriente - 005-5",
    "República Oriente - 011-0",
    "República y Guanajuato - 218-9",
    "Residencial Saltillo 2000, Portal del Quijote, San José de las Flores - 575-1",
    "Residencial Valle de las Palmas, Fracc. Oasis, Nueva España - 190-3",
    "Rubén Jaramillo, Loma Bonita - 267-2",
    "Rincón de los Pastores - 420-2",
    "Rancho de Peña - 492-3",
    "Rubén Jaramillo - 267-3",
    "Saltillo 2000 - 403-9",
    "Saltillo 2000 - 540-2",
    "Saltillo 2000 - 540-8",
    "Saltillo 2000 - 541-2",
    "Saltillo 2000 4ta. Ampliación - 571-3",
    "Satélite Norte - 193-7",
    "Saltillo 400 y Europa - 209-A",
    "San Agustín - 428-9",
    "San Ángel, San José, Puerta del Rey, Emimliano Zapata - 494-6",
    "San Isidro, Zona Centro - 021-4",
    "San José y Ampl. San José - 451-8",
    "San Juanita, 12 Oct, 23 Nov, El Progreso, Carmen Cavazos - 440-A",
    "San José de los Cerritos - 222-5",
    "San José de los Cerritos - 223-A",
    "San José y Ampl. San José, Nuevo Progreso - 450-3",
    "San Lorenzo (Frente a la UAAAN), Sierra del Sur - 185-2",
    "Santa Luz Analco (CL 33) - 167-9",
    "Santa Luz Analco - 157-9",
    "San Nicolás de los Berros - 513-9",
    "San Patricio - 303-0",
    "San Patricio, Fátima y Jacarandas Jardín - 137-3",
    "San Patricio, Quinta Córdova, San Alberto, Valle Real - 549-9",
    "San Ramón (21 de Marzo - P. de la Reforma - LEA - 10 de Mayo - Escuela) - 245-6",
    "Santos Saucedo, Ampliación Santos Saucedo - 140-A",
    "Satélite Norte - 194-1",
    "Satélite Sur - 305-A",
    "Satélite sur - 304-5",
    "Sierra Blanca - 559-2",
    "Sin Asignación de colonia - 010-6",
    "Sin Asignación de colonia - 051-5",
    "Sin Asignación de colonia - 132-0",
    "Sin Asignación de colonia - 203-0",
    "Sin Asignación de colonia - 208-8",
    "Sin Asignación de colonia - 396-7",
    "Sin Asignación de colonia - 369-7",
    "Sin Asignación de colonia - 374-0",
    "Sin Asignación de colonia - 377-4",
    "Sin Asignación de colonia, Anda Lucía - 393-3",
    "Sin Asignación de colonia - 397-1",
    "Sin Asignación de colonia - 422-1",
    "Sin Asignación de colonia - 469-5",
    "Sin población - 416-6",
    "Sin población - 410-9",
    "Sin Población - 400-5",
    "Sin población - 417-0",
    "Sin población - 422-1",
    "Sin nombre la colonia - 547-A",
    "Teresitas - 508-A",
    "Teresitas - 575-3",
    "Teresitas - 578-5",
    "Teresitas, Colinas del Sur - 509-4",
    "Teresitas, Nuevo Teresitas - 510-7",
    "Tierra y Libertad, Nogalera, Nuevo Amanecer, La Morita - 444-8",
    "Topochico - 237-1",
    "Topochico - 238-6",
    "Torrecillas, Los Ramones, Cieneguilla, Rosales de la Aurora, Ciudadela, San Luis, Manantiales de la Aurora, La herradura, Rancho la Joya y San José - 565-8",
    "Toreo, Rincón del TOreo, Los Ramones - 550-1",
    "Torremolinos, Villa Magna - 057-7",
    "UAAAN, Rastro Municipal, Sin población - 187-1",
    "Universidad Pueblo - 265-3",
    "Valle de las Flores - 516-4",
    "Valle de las Flores y Praderas - 220-6",
    "Valle Escondido - 529-1",
    "Valle Real, Cedros - 044-5",
    "Vicente Guerrero - 288-4",
    "Villa Sol - 169-8",
    "Vicente Guerrero - 469-8",
    "Valle de las Flores - 517-9",
    "Valle de las Flores Popular, Universo y parte Rincón de Guadalupe - 241-8",
    "Villa De Guadalupe, Torresillas, La Cienguita, Conejo Ixtlero, Rosales de la Aurora - 566-2",
    "Villa de San Miguel, Valle Real - 491-2",
    "Villa Morelos, Facc. Colibrí - 563-9",
    "Vista Hermosa, La Fuente y Morelos -247-5",
    "Venustiano Carranza y Valle Escondido Norte - 233-3",
    "Valle Azteca, Valle de las Flores - 483-8",
    "Valle de las Torres, Fracc. Valle - 570-9",
    "Valle Poniente - 157-5",
    "Zona Centro - 067-0",
    "Zona centro, La Joya - 019-7",
    "Zona Centro (Ramón Corona - Abasolo - Pérez Treviño) - 025-2",
    "Zona Centro - 023-3",
    "Zona Centro - 019-7",
    "Zona Industrial - 080-6",
    "Zona Centro (Gral. Cepeda - Allende, Múzquiz - Coss) - 017-8",
    "Zona Centro (Mariano Abasolo, Melchor Muzquiz, Benito Juárez) - 024-8",
    "Zona Centro (Otilio González - Rio Nazas) - 258-3",
    "Zona Centro - 029-0",
    "Zona Centro, Centenario, Santa Anita (20 de Noviembre - Jesús Nuncio - Rómulo Hernández - Zarco - Leona Vicario - Abasolo) - 263-4",
    "Zona Centro (Ramón Corona - Pedro Agüero)- 019-7",
    "Zaragoza - 307-9",
    "Zaragoza 4to Sector - 474-9",
    "Zaragoza - 535-7",
    "Zamora, COl. Ejército Constitucional - 022-9",
    "Zaragoza, Fracc. Residencial Sección 38 - 536-1",
    "Zaragoza - 467-9",
    "Zona centro (Múzquiz y Pte. Cárdenas) - 016-3",
    "Zona Centro (Abasolo, Corona) - 025-2",
    "7 de Noviembre y 26 de Marzo - 285-0",
    "23 de Noviembre 440-A - 439-7",
    "15 de Abril - 436-3",
    "15 de Abril - 437-6",
    "26 de Marzo y Ampl. 26 de Marzo - 286-5",
    "26 de Marzo y Ampl. Girasol - 289-9",
    "69 Batallón (Esc y Kinder Pertenece CL 89) - 421-7",
    "(Pertenece a SSA pero las escuelas pertenecen a la Clínica 70) - 304-5",
    "Barrio Santa Anita 028-6",
    "Otro"
];